### ISSUE TITLE
Update package on https://pypi.python.org

### ISSUE THREAD

**Issue by pzaytsev** [rhevm-qe-automation/pytest_jira#1]
On https://pypi.python.org/pypi/pytest-jira/0.01 is an old version of project. It causes error.
...
  File &quot;/mnt/tc-agent/a9343a0aef23cede/venv/local/lib/python2.7/site-packages/pytest_jira.py&quot;, line 95, in pytest_runtest_makereport
    rep.wasxfail = &quot;reason: &quot; + call.excinfo.value.msg
AttributeError: &apos;error&apos; object has no attribute &apos;msg&apos;

On github pytest_runtest_makereport function differes with same function in tar.gz on pypi.python.org.

**Comment by lukas-bednar** [comment]
@jlaska could you please add me as maintainer on python index of this package, in order to be able release new versions.

my username is "lukas-bednar"

**Comment by jlaska** [comment]
@lukas-bednar pypi seems to be having trouble atm ... I'll try again later.

**Comment by jlaska** [comment]
@lukas-bednar okay, you've been added as an _owner_ of `pytest-jira` on pypi.  Thanks for your help!

**Comment by lukas-bednar** [comment]
@jlaska thanks man! I will do my best! :smile:

**Comment by lukas-bednar** [comment]
released 0.2.0 https://pypi.python.org/pypi/pytest-jira
