### ISSUE TITLE
Due to change in mypermissions endpoint, connection can't be made

### ISSUE THREAD

**Issue by gs202** [rhevm-qe-automation/pytest_jira#111]
Jira has announced changes to /rest/api/2/mypermissions (Get my permissions) endpoint, this causes 400 error on connection
Error:
`'{"errorMessages":["The \'permissions\' query parameter is required."],"errors":{}}'`

**Comment by gs202** [comment]
@lukas-bednar i'd like to solve it

**Comment by ajeain** [comment]
hey, when is the fix expected to be released? Any workaround in the meantime? Is the issue only in this plugin or also a fix is needed by Attlassian? thank you

**Comment by lukas-bednar** [comment]
@gs202 Thank you for a fix.

@ajeain I believe it is an issue of this plugin. I have merged #113 and released new version [0.3.14](https://pypi.org/project/pytest-jira/0.3.14/) . Sorry for delaying that ...

**Comment by ajeain** [comment]
now, with the new version, I am getting the following error:
\INTERNALERROR>     elif not r.json()['permissions']['BROWSE']['havePermission']:
INTERNALERROR> KeyError: 'BROWSE'

**Comment by gs202** [comment]
@lukas-bednar  @ajeain missed that on my fix, sorry.
Opened a new PR to solve this issue #114
