### ISSUE TITLE
Change token_bearer to the new api required by jira

### ISSUE THREAD

**Issue by kazarski** [rhevm-qe-automation/pytest_jira#131]
On this page: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/
it says that we should change the Authorization key in the header of API request to "Basic <Token>" instead of "Bearer <Token> as it is now.
The proposed solution is just to rename Bearer to Basic in the file pytest_jira at line 192

**Comment by lukas-bednar** [comment]
Hello, thank you for bringing this change to my attention. Would you mind submitting a patch for that? I would be more than happy to review it, and get it in.

**Comment by lukas-bednar** [comment]
Actually we support both options. Token (with Bearer) and User&Password (with Basic). I guess we can close this issue. Feel free to re-open it if you don't agree!
