### ISSUE TITLE
How to apply mark.jira to only an iteration of parameterized test

### ISSUE THREAD

**Issue by tome-autonomous** [rhevm-qe-automation/pytest_jira#132]
I am attempting to make one of the test iterations marked with the plugin's custom marker but I am not able to achieve it:
This does not work:
`if test_id == "both_allow":
            pytest.mark.jira("PD-2366")`

It does work using the default pytest markers, which seem to not require using 'mark' in this case:
`if test_id == "both_allow":
            pytest.xfail(reason="Not testing both allow")`

I am wondering if there is a way to achieve this with the jira marker. It does work if I add the marker to the test itself: @pytest.mark.jira("PD-2366") but then all iterations are affected

**Comment by lukas-bednar** [comment]
Hello, please try to use a fixture, an example is here: https://github.com/rhevm-qe-automation/pytest_jira#fixture-usage

**Comment by lukas-bednar** [comment]
Feel free to re-open it if you don't find the suggestion from the above comment helpful.
