### ISSUE TITLE
Improve reading of config file and cover by tests

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/pytest_jira#27]
Add more locations:

* jira.cfg
* ~/jira.cfg
* /etc/jira.cfg

**Comment by vkondula** [comment]
We could replace jira.cfg by pytest ini files. #36 
that gives us pytest.ini, setup.cfg and tox.ini in multiple location as specified here https://pytest.org/latest/customize.html#initialization-determining-rootdir-and-inifile

**Comment by lukas-bednar** [comment]
@vkondula can we close this ticket ? I think you covered it in #37, right?

**Comment by vkondula** [comment]
Yes, we can close it. As you said, it's covered by #37 .
