### ISSUE TITLE
Pass pytest Plugins Compatibility

### ISSUE THREAD

**Issue by lukas-bednar** [rhevm-qe-automation/pytest_jira#33]
http://plugincompat.herokuapp.com
https://github.com/pytest-dev/plugincompat

related to #32 as well

**Comment by lukas-bednar** [comment]
we are green: http://plugincompat.herokuapp.com/

in additional we need to remove following info from that page:
```
... such as pytest-jira, which requires a jira server ....
```
which is not true anymore

**Comment by vkondula** [comment]
@lukas-bednar those tests indeed needs jira server (they were added to pass the coverage)

**Comment by lukas-bednar** [comment]
@vkondula ok, closing as well.
