### ISSUE TITLE
Add detailed reason when skipping/xfailing/xpassing

### ISSUE THREAD

**Issue by liiight** [rhevm-qe-automation/pytest_jira#68]
It would be great if the `reason` args could be filled when tests are skipped/xfailed/xpassing.
Something like "Skipped due to issue XXX-1111 being unresolved"

**Comment by lukas-bednar** [comment]
Good point!

In case that parameter ``run=False``, it should provide link to issue:
https://github.com/rhevm-qe-automation/pytest_jira/blob/master/pytest_jira.py#L103
But in other cases, it doesn't provide anything ... I will see how I can cover these cases as well ...

Thank you.

**Comment by liiight** [comment]
Sure, thank you for the plugin

**Comment by lukas-bednar** [comment]
Solved in #91
