### ISSUE TITLE
Internal Error when editing customfield

### ISSUE THREAD

**Issue by yamaturkey** [rhevm-qe-automation/pytest_jira#86]
I am trying to edit issue using issue.update(fields={'customfiled_10000':'edited'})

it returns response text = {"errorMessages":["Internal server error"],"errors":{}}

I can create issue and edit comments fine. Just not able to edit customfield.

Could someone help?

**Comment by yamaturkey** [comment]
when I create a new issue

issue= jira.create_issue(fields=root_dict)
and i can edit this issue oject with no problem

However, when I get the existing issue using

issue = jira.issue('JRA-123')
it gives me internal error.

**Comment by lukas-bednar** [comment]
@yamaturkey Thank you for opening issue,
could you please elaborate how I can reproduce your issue using this plugin?

As far as I am aware of, this plugin doesn't create issues in jira.
This plugin doesn't give you option to edit objects in jira, it only reads data.

**Comment by yamaturkey** [comment]
New findings, I was actually able to use the update method to edit issue on a different database.

I think this is the database server issue. I have contacted IT to look into this. Thanks~!
