### ISSUE TITLE
Make plugin workable for oauth connection type

### ISSUE THREAD

**Issue by ghost** [rhevm-qe-automation/pytest_jira#88]
Jira has ability enable oauth authentication. 
Read here about details what should be done from python code side. 
https://jira.readthedocs.io/en/master/examples.html#oauth

**Comment by liiight** [comment]
Personally I feel that automated operations, like this test plugin, API keys are a much better fit as they are easier to implement and revoke. But that's just my opinion...

**Comment by yoram-s** [comment]
This issue has high important for us, the pass my changed every few month, causing us account lock
I'd appreciate pushing this feature sooner

**Comment by yoram-s** [comment]
Almost one year has past since my last comment. Can you **please** priorities this request

**Comment by myakove** [comment]
@yoram-s is this answer your needs? #119

**Comment by yoram-s** [comment]
looking forward to see this PR #119 integrated and part of this plugin

**Comment by lukas-bednar** [comment]
Fixed in https://github.com/rhevm-qe-automation/pytest_jira/pull/119
