### ISSUE TITLE
jira_issue fixture should return issue with metadata

### ISSUE THREAD

**Issue by liiight** [rhevm-qe-automation/pytest_jira#94]
I propose that the `jira_issue` fixture will return a `JiraIssue` model which will hold metadata in its attributes (like description, dates etc.).

This will enable a richer experience for both returning detailed skip messages, more complex conditional statements and more, all using data we already fetch but do nothing with.
 
The class will have a `__bool__` dunder which will make previously the class backwards compatible with previous conditional checks on the fixture reply. 

If you approve I'd be happy to put a PR for this.

WDYT?

**Comment by lukas-bednar** [comment]
Big thumb for this!!

**Comment by liiight** [comment]
Cool, I'll put up a PR

**Comment by lukas-bednar** [comment]
I would stick to most common ones, which are mostly used in decision making to skip or not-skip the issue.

**Comment by liiight** [comment]
Maybe we should read the Jira dependency. It didn't make much sense to use it just for authentication but it does for returning rich data.

**Comment by liiight** [comment]
@lukas-bednar ping

**Comment by lukas-bednar** [comment]
On one hand I like the fact that this plugin became more lightweight by replacing `jira` module with `requests`.

But if it leads us to reinvent existing code, I would rather step back and use `jira` dependency instead.

So, yes I agree with your statement.

**Comment by liiight** [comment]
awesome. i'll make the changes. just to make sure, we're talking about using https://pypi.org/project/jira/, correct?

**Comment by lukas-bednar** [comment]
yes

**Comment by gs202** [comment]
Hi @lukas-bednar i'd like to take this feature.
Thought about adding additional Boolean addoption which will return the JiraIssue

**Comment by gs202** [comment]
I think that this can be closed

**Comment by liiight** [comment]
Closed with #108
